language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 6.0
env:
  - PROJECTNAME=FewBox.Template.Service
script:
  - dotnet pack --output nupkg $TRAVIS_BUILD_DIR/$PROJECTNAME.csproj
after_success:
  - dotnet nuget push $TRAVIS_BUILD_DIR/nupkg/$PROJECTNAME.*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json