language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
env:
  # Docker slug
  - DOCKER_REPO_SLUG=fewbox/FB_SERVICE PROJECTNAME=FewBox.Template.Service PROJECTUNITTESTNAME=$PROJECTNAME.UnitTest
install:
  - dotnet restore $PROJECTNAME
script:
  - dotnet publish -c Release $PROJECTNAME/$PROJECTNAME.csproj -p:FileVersion=$TRAVIS_JOB_NUMBER
  - cd $TRAVIS_BUILD_DIR/$PROJECTNAME/bin/Release/net6.0/publish
  - cp $TRAVIS_BUILD_DIR/Dockerfile ./
  - cp $TRAVIS_BUILD_DIR/.dockerignore ./
  # build latest image always
  - docker build -t $DOCKER_REPO_SLUG:latest .
  # build the tagged image
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker build -t $DOCKER_REPO_SLUG:$TRAVIS_BRANCH .; else true ; fi
after_success:
  # IMPORTANT! Add the environment variables in Travis Build Environment (one time!)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push to latest if master branch
  - if [[ $TRAVIS_BRANCH = master ]]; then docker push $DOCKER_REPO_SLUG:latest; else true; fi
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker push $DOCKER_REPO_SLUG:$TRAVIS_TAG; else true ; fi